version: '3.8'

services:
  api:
    build:
      dockerfile: docker/php/dockerfile
    volumes:
      - ./api:/var/www/apiPlatform
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=api.local
    container_name: apiPlatform_api
    networks:
      - apiPlatform

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/apiPlatform
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: apiPlatform_nginx
    networks:
      - apiPlatform
    depends_on:
      - api

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ../databases/apiPlatform:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apiPlatform
      MYSQL_USER: apiPlatform
      MYSQL_PASSWORD: apiPlatform
    container_name: apiPlatform_mysql
    networks:
      - apiPlatform

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: apiPlatform_redis
    networks:
      - apiPlatform

  web:
    image: node:20.11.1
    volumes:
      - ./web:/app
    working_dir: /app
    command: npm start
#    command: tail -f /dev/null
    container_name: apiPlatform_web
    ports:
      - "3000:3000"

networks:
  apiPlatform:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
